name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to SWR
        uses: docker/login-action@v3
        with:
          registry: swr.cn-north-4.myhuaweicloud.com
          username: ${{ secrets.SWR_USERNAME }}
          password: ${{ secrets.SWR_PASSWORD }}

      - name: Build and Push Backend
        run: |
          cd part1/backend
          docker build --provenance=false -t swr.cn-north-4.myhuaweicloud.com/cloud-course-ks/backend:${{ github.sha }} .
          docker push swr.cn-north-4.myhuaweicloud.com/cloud-course-ks/backend:${{ github.sha }}

      - name: Build and Push Frontend
        run: |
          cd part1/frontend
          docker build --provenance=false -t swr.cn-north-4.myhuaweicloud.com/cloud-course-ks/frontend:${{ github.sha }} .
          docker push swr.cn-north-4.myhuaweicloud.com/cloud-course-ks/frontend:${{ github.sha }}
